name: Bump version and update build.gradle

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Bump version and create Git tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false

      - name: Update version in build.gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: "> gradlew setVersion -PnewVersion=${GITHUB_REF#refs/tags/}"

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v7
        with:
          add: 'app/build.gradle'
          message: "Bump version to ${GITHUB_REF#refs/tags/}"
          author_name: "GitHub Actions"
          author_email: "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
